# Generated by Django 3.2.6 on 2021-09-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0002_auto_20210905_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='emailId',
        ),
    ]
