# Generated by Django 3.2.6 on 2021-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0004_auto_20210905_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
