# Generated by Django 3.2.6 on 2021-09-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0006_auto_20210905_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trelloAPIs.Cards.created_by+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trelloAPIs.Projects.created_by+', to=settings.AUTH_USER_MODEL),
        ),
    ]
