# Generated by Django 3.2.6 on 2021-09-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0007_auto_20210906_0948'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
