# Generated by Django 3.2.6 on 2021-09-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0010_alter_cards_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='project_lists',
        ),
        migrations.AddField(
            model_name='lists',
            name='lists_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_lists', to='trelloAPIs.projects'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cards_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_cards', to='trelloAPIs.lists'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(related_name='projects_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
