# Generated by Django 3.2.6 on 2021-09-08 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0011_auto_20210908_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='card_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_in_card', to='trelloAPIs.cards'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
