# Generated by Django 3.2.6 on 2021-09-08 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0013_alter_projects_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cards',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
