# Generated by Django 3.2.6 on 2021-09-09 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0014_auto_20210908_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='admins',
            field=models.ManyToManyField(related_name='projects_of_user_as_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
