# Generated by Django 3.2.6 on 2021-10-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0016_alter_comments_comment_tym'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
