# Generated by Django 3.2.6 on 2021-10-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloAPIs', '0017_cards_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='completed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
